# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/napkin_tasks',
                'doc_host': 'https://hgzech.github.io',
                'git_url': 'https://github.com/hgzech/napkin_tasks',
                'lib_path': 'napkin_tasks'},
  'syms': {'napkin_tasks.core': {'napkin_tasks.core.foo': ('core.html#foo', 'napkin_tasks/core.py')}}}
